# Generated by Django 3.2.16 on 2022-11-26 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221126_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
