# Generated by Django 3.2.16 on 2022-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221126_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
